spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:login-service;DB_CLOSE_DELAY=-1
    name:
    username:
    password:
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show_sql: true
    generate-ddl: true
security:
  basic:
    enabled: false
---
spring:
  profiles:
    active: dev, default
  datasource:
    url: jdbc:h2:mem:login-service;DB_CLOSE_DELAY=-1
    name:
    username:
    password:
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show_sql: true
    generate-ddl: true